[Variables]
APIKey=

;https://tumblr2rss.obstack.net/
;this was the last thing i worked on and my motivation was gone so rather than actually using an API i just used another cool project that turns your tumblr dashboard into an rss feed. There is nothing sus about it but I'm always extra secure by default so i just created a burner tumblr account, then from that one looked up my main account and followed all the same blogs log in, get your rss URL, and plug it in as the "APIKey" above. maybe one day I'll do it right...